// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.joyxj.proto;

public interface StudentListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.joyxj.proto.StudentListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.joyxj.proto.StudentResponse studentResonse = 1;</code>
   */
  java.util.List<StudentResponse>
      getStudentResonseList();
  /**
   * <code>repeated .com.joyxj.proto.StudentResponse studentResonse = 1;</code>
   */
  StudentResponse getStudentResonse(int index);
  /**
   * <code>repeated .com.joyxj.proto.StudentResponse studentResonse = 1;</code>
   */
  int getStudentResonseCount();
  /**
   * <code>repeated .com.joyxj.proto.StudentResponse studentResonse = 1;</code>
   */
  java.util.List<? extends StudentResponseOrBuilder>
      getStudentResonseOrBuilderList();
  /**
   * <code>repeated .com.joyxj.proto.StudentResponse studentResonse = 1;</code>
   */
  StudentResponseOrBuilder getStudentResonseOrBuilder(
          int index);
}
