// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.joyxj.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_joyxj_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_joyxj_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_joyxj_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_joyxj_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_joyxj_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_joyxj_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_joyxj_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_joyxj_proto_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_joyxj_proto_StudentListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_joyxj_proto_StudentListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\017com.joyxj.proto\"\035\n\tMyRe" +
      "quest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyResponse\022\020\n" +
      "\010realname\030\001 \001(\t\"\035\n\016StudentRequest\022\013\n\003age" +
      "\030\001 \001(\005\":\n\017StudentResponse\022\014\n\004name\030\001 \001(\t\022" +
      "\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"O\n\023StudentLis" +
      "tResponse\0228\n\016studentResonse\030\001 \003(\0132 .com." +
      "joyxj.proto.StudentResponse2\245\002\n\016StudentS" +
      "ervice\022R\n\025GetRealNameByUserName\022\032.com.jo" +
      "yxj.proto.MyRequest\032\033.com.joyxj.proto.My" +
      "Response\"\000\022Y\n\020GetStudentsByAge\022\037.com.joy" +
      "xj.proto.StudentRequest\032 .com.joyxj.prot" +
      "o.StudentResponse\"\0000\001\022d\n\027GetStudentWrapp" +
      "erByAges\022\037.com.joyxj.proto.StudentReques" +
      "t\032$.com.joyxj.proto.StudentListResponse\"" +
      "\000(\001B!\n\017com.joyxj.protoB\014StudentProtoP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_joyxj_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_joyxj_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_joyxj_proto_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_joyxj_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_joyxj_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_joyxj_proto_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_com_joyxj_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_joyxj_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_joyxj_proto_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_com_joyxj_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_joyxj_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_joyxj_proto_StudentResponse_descriptor,
        new String[] { "Name", "Age", "City", });
    internal_static_com_joyxj_proto_StudentListResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_joyxj_proto_StudentListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_joyxj_proto_StudentListResponse_descriptor,
        new String[] { "StudentResonse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
